/**
 * PDF Report i18n Translations
 */

export const pdfTranslations = {
  en: {
    reportTitle: 'Raawi X Accessibility Report',
    subtitle: 'Comprehensive Digital Accessibility Audit',
    entityLabel: 'Entity',
    propertyLabel: 'Property',
    scanDateLabel: 'Scan Date',
    entityCodeLabel: 'Entity Code',
    introductionTitle: 'Introduction',
    reportGeneratedOn: 'Report Generated On',
    executiveSummaryTitle: 'Executive Summary',
    wcagALabel: 'WCAG A Compliance',
    wcagAALabel: 'WCAG AA Compliance',
    needsReviewLabel: 'Needs Review',
    scanStatisticsTitle: 'Scan Statistics',
    totalPagesLabel: 'Total Pages Scanned',
    totalFindingsLabel: 'Total Findings',
    failedRulesLabel: 'Failed Rules',
    needsReviewRulesLabel: 'Rules Needing Review',
    keyFindingsTitle: 'Key Findings',
    topFindingsTitle: 'Top Findings',
    wcagIdHeader: 'WCAG ID',
    levelHeader: 'Level',
    statusHeader: 'Status',
    descriptionHeader: 'Description',
    pageHeader: 'Page',
    footerText: 'This report was generated by Raawi X Accessibility Platform',
    reportGeneratedBy: 'Generated by',
    disclaimerText: 'Scores reflect scanned pages and crawl scope; this is not a certification.',
    partialReportSubtitle:
      'Partial results — scan did not complete; findings reflect pages processed before stop or failure.',
    interimExportSubtitle:
      'Interim export — scan may still be running; includes only results saved in the database at export time.',
  },
  ar: {
    reportTitle: 'تقرير إمكانية الوصول - راوي إكس',
    subtitle: 'فحص شامل لإمكانية الوصول الرقمي',
    entityLabel: 'الجهة',
    propertyLabel: 'الموقع',
    scanDateLabel: 'تاريخ الفحص',
    entityCodeLabel: 'رمز الجهة',
    introductionTitle: 'المقدمة',
    reportGeneratedOn: 'تم إنشاء التقرير في',
    executiveSummaryTitle: 'الملخص التنفيذي',
    wcagALabel: 'امتثال WCAG A',
    wcagAALabel: 'امتثال WCAG AA',
    needsReviewLabel: 'يحتاج مراجعة',
    scanStatisticsTitle: 'إحصائيات الفحص',
    totalPagesLabel: 'إجمالي الصفحات المفحوصة',
    totalFindingsLabel: 'إجمالي النتائج',
    failedRulesLabel: 'القواعد الفاشلة',
    needsReviewRulesLabel: 'القواعد التي تحتاج مراجعة',
    keyFindingsTitle: 'النتائج الرئيسية',
    topFindingsTitle: 'أهم النتائج',
    wcagIdHeader: 'معيار WCAG',
    levelHeader: 'المستوى',
    statusHeader: 'الحالة',
    descriptionHeader: 'الوصف',
    pageHeader: 'الصفحة',
    footerText: 'تم إنشاء هذا التقرير بواسطة منصة راوي إكس لإمكانية الوصول',
    reportGeneratedBy: 'تم الإنشاء بواسطة',
    disclaimerText: 'تعكس الدرجات الصفحات المفحوصة ونطاق الزحف؛ هذا ليس شهادة.',
    partialReportSubtitle:
      'نتائج جزئية — لم يكتمل المسح؛ تعكس النتائج الصفحات التي تمت معالجتها قبل الإيقاف أو الفشل.',
    interimExportSubtitle:
      'تصدير مؤقت — قد يكون المسح لا يزال قيد التشغيل؛ يشمل فقط النتائج المحفوظة في قاعدة البيانات وقت التصدير.',
  },
};

export function getPDFTranslation(key: keyof typeof pdfTranslations.en, locale: 'en' | 'ar'): string {
  return pdfTranslations[locale][key] || pdfTranslations.en[key];
}

